language: node_js
script: npm test
node_js:
- node
- io.js
- '0.12'
notifications:
  email:
  - eng+build+wealthfrontjavascript@wealthfront.com
deploy:
  provider: npm
  email: ops+npm@wealthfront.com
  api_key:
    secure: mzyVPsMfX0pCEX2O+klf2Kr2sjl9XpK1qwaaiq9mvnAkPNjrMxBxNwtJ+oRY+fnRrgYyino11tQPB2YkxcQXJf2jnSiP9hJB19zRMsZ0UETwexMAwVs/cGR2EX8ZadiM7ZlbkuIH1ZWRiCYxuSpebYB2GG6hR06YUmB7y429ZlV5yzXE0YZAdK76018fCvb07q8h93ZA9FUFZXNC2IFMNbiWDXVaV8Z+0BJNRf/S55eucMoVpS/ReRqt++rC5Jd69+e2YP3gsWlo1QHyhnscl2zugMsCvGw5v7my2YKN86MwIyYpGVPACCYulkR80ElLaUTGDzFXodxNl+1SObmLF4kyxsbLw01UQnwR8VxTbZR6UNRIFgtvo5OE6qPBgPaKtZ/6sK0fNk3YpI7AaFOeR8j60rBLphktZOSuyy3+bfUtpGDyqB/To2Us7gPTkiH6HLrQKR9Gwfeam6wGhpWhdsQRbknZoBtVDSfELd5DLYhBXbSgPOXYhNXmPmPziJWM9Ev+mc5HL/w4EDwCEq8+U8Q8SK4oLb5JXrxU4XbOcYT5aKlpC7Nh5hV+Wk9OJ80BpDVSjstRm9QvYNaXQo+9Nu3EWbvJClk+Tmsdri/x22ehy4rMDdnOHlUxY3qQq5EjNJZrRhZ0wFXdVkhXEt+Pv95eXfkwLgbTbUtq0SKAq3g=
  on:
    tags: true
    repo: wealthfront/javascript
    node: '0.12'
